### ISSUE TITLE
Drop localForage in favour of PouchDB local docs

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/angular-eha.login-service#2]
Since we've already a dependency on PouchDB, couldn't we just reuse it for local storage get/set and thereby remove the need for localForage (+ wrappers)? This seems like a good use case for [local docs](http://pouchdb.com/guides/local-documents.html).

**Comment by remy** [comment]
I'm keen to drop localForge support (I already refactored out our own eha wrapper to localForge!).

It should be straightforward since I'm wrapping the storage calls - so changing the source of the store is simple. However, I'm not familiar enough with pouch to know how to use it (quickly) to solve this issue. I'm happy to take some directions to update...?
